"""few new rows

Revision ID: b4624263be3b
Revises: 58a9bfda5fe7
Create Date: 2024-07-13 13:01:01.958565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4624263be3b'
down_revision = '58a9bfda5fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['path'])

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('dominant_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('favourite', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['filename', 'folder_id'])
        batch_op.drop_column('title')
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('favourite')
        batch_op.drop_column('dominant_color')
        batch_op.drop_column('filename')

    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
